[package]
name = "capralink"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[[bin]]
name = "capralink"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
capralink_engine = { path = "../engine" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
